[package]
name = "sun_rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-xdr = "*"
serde = { version = "*", features = ["derive"] }
xdr_extras = { version = "*", path = "../xdr_extras" }
